### ISSUE TITLE
REI warning

### ISSUE THREAD

**Issue by alkerss** [costamiri/HollowWoods#7]
MC: 1.19.2
Fabric: 0.14.10
Mod version: HollowWoods 1.2.2 for 1.19.2
Issue: When launching Roughly Enough Items with HollowWoods, it posts a warning on game launch.
The Warning:
Warnings during Roughly Enough Items initialization
The Entrypoint used by HollowWoods, "rei" is deprecated and will be removed in a future version of Roughly Enough Items. Please use "rei_server", "rei_client" or "rei_common" instead.

**Comment by DadoIrie** [comment]
why is this issue being closed as completed? just a friendly meant question - because it does lead to a server crash for me

![image](https://github.com/costamiri/HollowWoods/assets/61109153/d1733566-0c29-4f39-aa8c-545466d6f287)

without hollow woods all good and server launches - would love to seeing this fixed
